"""Tests for :func:`spotify_scraper.api.parse_entities.parse_transcript`."""

from __future__ import annotations

from typing import Any

import pytest

from spotify_scraper.api.parse_entities import parse_transcript
from spotify_scraper.errors import ParsingError


def _payload(**overrides: Any) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "language": "en",
        "provider": "Spotify",
        "isAutoGenerated": True,
        "lines": [
            {"start_ms": 0, "text": "Welcome to the show."},
            {"start_ms": 4200, "text": "Today we talk about transcripts."},
        ],
    }
    payload.update(overrides)
    return payload


def test_parses_lines() -> None:
    transcript = parse_transcript(_payload())
    assert transcript.language == "en"
    assert transcript.provider == "Spotify"
    assert transcript.is_auto_generated is True
    assert len(transcript.lines) == 2
    assert transcript.lines[0].start_ms == 0
    assert transcript.lines[0].text == "Welcome to the show."
    assert transcript.lines[1].start_ms == 4200


def test_start_ms_is_non_negative_int() -> None:
    transcript = parse_transcript(_payload())
    assert all(isinstance(line.start_ms, int) and line.start_ms >= 0 for line in transcript.lines)


def test_empty_text_lines_are_dropped() -> None:
    transcript = parse_transcript(
        _payload(
            lines=[
                {"start_ms": 0, "text": ""},
                {"start_ms": 1000, "text": "real line"},
                {"start_ms": 2000},
            ]
        )
    )
    assert len(transcript.lines) == 1
    assert transcript.lines[0].text == "real line"


def test_string_start_ms_is_accepted() -> None:
    transcript = parse_transcript(_payload(lines=[{"start_ms": "5000", "text": "hi"}]))
    assert transcript.lines[0].start_ms == 5000


def test_unparsable_start_ms_falls_back_to_zero() -> None:
    transcript = parse_transcript(_payload(lines=[{"start_ms": "abc", "text": "hi"}]))
    assert transcript.lines[0].start_ms == 0


def test_defaults_when_metadata_absent() -> None:
    transcript = parse_transcript({"lines": [{"start_ms": 0, "text": "x"}]})
    assert transcript.language is None
    assert transcript.provider is None
    assert transcript.is_auto_generated is None


def test_missing_lines_container_raises() -> None:
    with pytest.raises(ParsingError):
        parse_transcript({"language": "en"})
