"""Tests for :mod:`spotify_scraper.api.transcripts` (URL, headers, decode)."""

from __future__ import annotations

from spotify_scraper.api import transcripts as transcripts_api

EPISODE_ID = "512ojhOuo1ktJprKbVcKyQ"


def test_transcript_url_isolated_endpoint() -> None:
    url = transcripts_api.transcript_url(EPISODE_ID)
    assert url == (
        f"https://spclient.wg.spotify.com/transcript-read-along/v2/episode/{EPISODE_ID}?format=json"
    )


def test_auth_headers() -> None:
    headers = transcripts_api.auth_headers("TOKEN123")
    assert headers == {"Authorization": "Bearer TOKEN123", "app-platform": "WebPlayer"}


# --- decode_envelope: the real transcript-read-along shape --------------------


def test_decode_envelope_spotify_section_shape() -> None:
    # Mirrors the live shape: a section[] of speaker `title` labels, spoken
    # `text.sentence`, and music `fallback.sentence`, with language at the top.
    body = {
        "language": "en-us",
        "timeSyncedStatus": "SYLLABLE_SYNCED",
        "section": [
            {"startMs": 0, "title": {"title": "Speaker 1"}},
            {"startMs": 0, "text": {"sentence": {"startMs": 0, "text": "Hello there."}}},
            {"startMs": 3000, "text": {"sentence": {"startMs": 3200, "text": "General Kenobi."}}},
            {"startMs": 9000, "fallback": {"sentence": {"startMs": 9000, "text": "Music playing"}}},
        ],
    }
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["language"] == "en-us"
    assert decoded["lines"] == [
        {"start_ms": 0, "text": "Hello there."},
        {"start_ms": 3200, "text": "General Kenobi."},
        {"start_ms": 9000, "text": "Music playing"},
    ]


def test_decode_envelope_generic_string_cues() -> None:
    # Tolerant fallback: a cue may carry its text directly as a string.
    body = {
        "language": "en",
        "provider": "Spotify",
        "isAutoGenerated": False,
        "section": [
            {"startMs": 0, "text": "Hello there."},
            {"timeMs": 3000, "transcription": "General Kenobi."},
        ],
    }
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["language"] == "en"
    assert decoded["provider"] == "Spotify"
    assert decoded["isAutoGenerated"] is False
    assert decoded["lines"] == [
        {"start_ms": 0, "text": "Hello there."},
        {"start_ms": 3000, "text": "General Kenobi."},
    ]


def test_decode_envelope_nested_json_container() -> None:
    body = {"timedText": {"segments": [{"start_ms": 1200, "transcription": "Nested cue."}]}}
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["lines"] == [{"start_ms": 1200, "text": "Nested cue."}]


def test_decode_envelope_no_lines_omits_lines_key() -> None:
    decoded = transcripts_api.decode_envelope({"language": "en"})
    assert "lines" not in decoded
    assert decoded["language"] == "en"


def test_decode_envelope_skips_titles_and_non_mappings() -> None:
    body = {
        "section": [
            "not a cue",
            {"startMs": 5, "title": {"title": "Host"}},
            {"startMs": 10, "text": {"sentence": {"startMs": 10, "text": "real"}}},
        ]
    }
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["lines"] == [{"start_ms": 10, "text": "real"}]
