"""Tests for :mod:`spotify_scraper.api.transcripts` (URL, headers, decode)."""

from __future__ import annotations

import base64

from spotify_scraper.api import transcripts as transcripts_api

EPISODE_ID = "512ojhOuo1ktJprKbVcKyQ"


def test_transcript_url_isolated_endpoint() -> None:
    url = transcripts_api.transcript_url(EPISODE_ID)
    assert url == (
        f"https://spclient.wg.spotify.com/transcript-read-along/v2/episode/{EPISODE_ID}?format=json"
    )


def test_auth_headers() -> None:
    headers = transcripts_api.auth_headers("TOKEN123")
    assert headers == {"Authorization": "Bearer TOKEN123", "app-platform": "WebPlayer"}


# --- decode_envelope: plain-JSON branch ---------------------------------------


def test_decode_envelope_plain_json() -> None:
    body = {
        "language": "en",
        "provider": "Spotify",
        "isAutoGenerated": False,
        "section": [
            {"startMs": 0, "text": "Hello there."},
            {"timeMs": 3000, "text": "General Kenobi."},
        ],
    }
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["language"] == "en"
    assert decoded["provider"] == "Spotify"
    assert decoded["isAutoGenerated"] is False
    assert decoded["lines"] == [
        {"start_ms": 0, "text": "Hello there."},
        {"start_ms": 3000, "text": "General Kenobi."},
    ]


def test_decode_envelope_nested_json_container() -> None:
    body = {"timedText": {"segments": [{"start_ms": 1200, "transcription": "Nested cue."}]}}
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["lines"] == [{"start_ms": 1200, "text": "Nested cue."}]


def test_decode_envelope_no_lines_omits_lines_key() -> None:
    decoded = transcripts_api.decode_envelope({"language": "en"})
    assert "lines" not in decoded
    assert decoded["language"] == "en"


# --- decode_envelope: base64-protobuf branch ----------------------------------


def _varint(value: int) -> bytes:
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            out.append(byte | 0x80)
        else:
            out.append(byte)
            return bytes(out)


def _len_delim(field_num: int, payload: bytes) -> bytes:
    tag = (field_num << 3) | 2
    return _varint(tag) + _varint(len(payload)) + payload


def _varint_field(field_num: int, value: int) -> bytes:
    tag = (field_num << 3) | 0
    return _varint(tag) + _varint(value)


def _transcription(*texts: str) -> bytes:
    # transcription message: field 1 = repeated string text.
    return b"".join(_len_delim(1, t.encode("utf-8")) for t in texts)


def _segment(time_ms: int, *texts: str) -> bytes:
    # segment message: field 2 = time_ms varint, field 3 = transcription message.
    return _varint_field(2, time_ms) + _len_delim(3, _transcription(*texts))


def _transcript_blob(segments: list[bytes]) -> bytes:
    # top-level message: field 4 = repeated segments.
    return b"".join(_len_delim(4, seg) for seg in segments)


def test_decode_envelope_base64_protobuf_vector() -> None:
    blob = _transcript_blob(
        [
            _segment(0, "Welcome", "to the show"),
            _segment(5500, "Second cue."),
        ]
    )
    body = {
        "language": "es",
        "transcript": base64.b64encode(blob).decode("ascii"),
    }
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["language"] == "es"
    assert decoded["lines"] == [
        {"start_ms": 0, "text": "Welcome to the show"},
        {"start_ms": 5500, "text": "Second cue."},
    ]


def test_decode_envelope_invalid_base64_omits_lines() -> None:
    decoded = transcripts_api.decode_envelope({"transcript": "not%%%base64"})
    assert "lines" not in decoded


def test_decode_envelope_protobuf_multibyte_varint() -> None:
    # time_ms = 300000 forces a multi-byte varint, exercising the shift path.
    blob = _transcript_blob([_segment(300000, "Late cue.")])
    body = {"transcript": base64.b64encode(blob).decode("ascii")}
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["lines"] == [{"start_ms": 300000, "text": "Late cue."}]


def test_decode_envelope_skips_non_mapping_cues() -> None:
    body = {"lines": ["not a cue", {"startMs": 10, "text": "real"}]}
    decoded = transcripts_api.decode_envelope(body)
    assert decoded["lines"] == [{"start_ms": 10, "text": "real"}]
