# Travis CI configuration for SpotifyScraper v2.0
language: python

# Use Ubuntu 20.04 LTS
dist: focal

# Cache dependencies
cache:
  pip: true
  directories:
    - $HOME/.cache/pip

# Test on multiple Python versions
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

# Install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -e ".[dev]"
  - pip install codecov

# Run tests
script:
  # Linting
  - black --check src/ tests/
  - isort --check-only src/ tests/
  - flake8 src/ tests/
  
  # Run tests with coverage
  - pytest --cov=spotify_scraper --cov-report=xml --cov-report=term tests/
  
  # Build the package
  - python -m build

# After success
after_success:
  - codecov

# Deploy to PyPI on tags
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: # PYPI_TOKEN needs to be encrypted
  on:
    tags: true
    python: "3.9"

# Notifications
notifications:
  email:
    recipients:
      - aliakhtari78@hotmail.com
    on_success: change
    on_failure: always