# Jekyll configuration for GitHub Pages
# This tells Jekyll to exclude all files except the ones we want

# Disable Jekyll processing
plugins: []

# Exclude everything except index.html
exclude:
  - "*.py"
  - "*.pyc"
  - "*.ini"
  - "*.cfg"
  - "*.toml"
  - "*.txt"
  - "*.json"
  - "*.sh"
  - "*.bat"
  - "*.ps1"
  - "Dockerfile"
  - "docker-compose.yml"
  - "Makefile"
  - "LICENSE"
  - "README.md"
  - "CHANGELOG.md"
  - "CODE_OF_CONDUCT.md"
  - "CONTRIBUTING.md"
  - "SECURITY.md"
  - "MANIFEST.in"
  - "setup.py"
  - "setup.cfg"
  - "pyproject.toml"
  - "pytest.ini"
  - "mypy.ini"
  - "tox.ini"
  - "mkdocs.yml"
  - "requirements*.txt"
  - ".github/"
  - "src/"
  - "tests/"
  - "docs/"
  - "examples/"
  - "scripts/"
  - "venv*/"
  - "wiki/"
  - "dist/"
  - "build/"
  - "htmlcov/"
  - "__pycache__/"
  - ".pytest_cache/"
  - ".tox/"
  - "*.egg-info/"
  - ".*"
  - "!.nojekyll"
  
# Only include the index.html and .nojekyll
include:
  - index.html
  - .nojekyll