# GitHub Pages Configuration
# Disable Jekyll processing entirely
plugins: []

# Only include these files
include:
  - index.html
  - README.md
  - LICENSE
  - .nojekyll

# Exclude everything else
exclude:
  - "*"
  - "**/*"
  - "!index.html"
  - "!README.md" 
  - "!LICENSE"
  - "!.nojekyll"