site_name: SpotifyScraper Documentation
site_author: Ali Akhtari
site_description: The Ultimate Python Library for Spotify Data Extraction - Version 2.0.0
site_url: https://spotifyscraper.readthedocs.io/
repo_url: https://github.com/AliAkhtari78/SpotifyScraper
repo_name: AliAkhtari78/SpotifyScraper
copyright: Copyright &copy; 2025 Ali Akhtari - Documentation Last Updated May 2025

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - announce.dismiss
  icon:
    logo: material/music-note
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Introduction: guide/index.md
    - Basic Usage: guide/basic-usage.md
    - Authentication: guide/authentication.md
    - Error Handling: guide/error-handling.md
    - Media Downloads: guide/media-downloads.md
  - API Reference:
    - Overview: api/index.md
    - Client: api/client.md
    - Extractors: api/extractors.md
    - Media: api/media.md
    - Utils: api/utils.md
    - Parsers: api/parsers.md
    - Exceptions: api/exceptions.md
  - Examples:
    - Overview: examples/index.md
    - Quick Start: examples/quickstart.md
    - CLI Usage: examples/cli.md
    - Bulk Operations: examples/bulk_operations.md
    - Advanced Usage: examples/advanced.md
    - Real-World Projects: examples/projects.md
  - Advanced Topics:
    - Overview: advanced/index.md
    - Architecture: advanced/architecture.md
    - Custom Extractors: advanced/custom-extractors.md
    - Performance: advanced/performance.md
    - Scaling: advanced/scaling.md
  - Additional Resources:
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
    - Migration Guide: migration.md
    - Changelog: changelog.md
    - Contributing: contributing.md
    - Features: features.md
    - Testing Guide: README_TESTING.md
    - MCP Testing: mcp_testing.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - codehilite:
      guess_lang: false
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version: 2.0.0
  author: Ali Akhtari
  year: 2025
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AliAkhtari78/SpotifyScraper
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/spotifyscraper/
  generator: false

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang:
        - en
  - minify:
      minify_html: true