site_name: SpotifyScraper Documentation
site_author: Ali Akhtari
site_description: The Ultimate Python Library for Spotify Data Extraction
site_url: https://spotifyscraper.readthedocs.io/
repo_url: https://github.com/AliAkhtari78/SpotifyScraper
repo_name: AliAkhtari78/SpotifyScraper
copyright: Copyright &copy; 2025 Ali Akhtari

theme:
  name: material

nav:
  - Home: index.md