site_name: SpotifyScraper Documentation
site_author: Ali Akhtari
site_description: The Ultimate Python Library for Spotify Data Extraction - Version 2.0.0
site_url: https://spotifyscraper.readthedocs.io/
repo_url: https://github.com/AliAkhtari78/SpotifyScraper
repo_name: AliAkhtari78/SpotifyScraper
copyright: Copyright &copy; 2025 Ali Akhtari - Documentation Last Updated May 2025

theme:
  name: readthedocs
  locale: en
  analytics:
    gtag: null
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
    - json
    - xml
  navigation_depth: 4
  collapse_navigation: false
  titles_only: false
  sticky_navigation: true
  prev_next_buttons_location: both
  include_search_page: true
  search_index_only: false

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Introduction: guide/index.md
    - Basic Usage: guide/basic-usage.md
    - Authentication: guide/authentication.md
    - Error Handling: guide/error-handling.md
    - Media Downloads: guide/media-downloads.md
  - API Reference:
    - Overview: api/index.md
    - Client: api/client.md
    - Extractors: api/extractors.md
    - Media: api/media.md
    - Utils: api/utils.md
    - Parsers: api/parsers.md
    - Exceptions: api/exceptions.md
  - Examples:
    - Overview: examples/index.md
    - Quick Start: examples/quickstart.md
    - CLI Usage: examples/cli.md
    - Bulk Operations: examples/bulk_operations.md
    - Advanced Usage: examples/advanced.md
    - Real-World Projects: examples/projects.md
  - Advanced Topics:
    - Overview: advanced/index.md
    - Architecture: advanced/architecture.md
    - Custom Extractors: advanced/custom-extractors.md
    - Performance: advanced/performance.md
    - Scaling: advanced/scaling.md
  - Additional Resources:
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
    - Migration Guide: migration.md
    - Changelog: changelog.md
    - Contributing: contributing.md
    - Features: features.md
    - Testing Guide: README_TESTING.md
    - MCP Testing: mcp_testing.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - codehilite:
      guess_lang: false
  - tables
  - attr_list
  - def_list
  - footnotes

extra:
  version: 2.0.0
  author: Ali Akhtari
  year: 2025

plugins:
  - search