site_name: SpotifyScraper Documentation
site_author: Ali Akhtari
site_description: The Ultimate Python Library for Spotify Data Extraction - Version 2.0.0
site_url: https://spotifyscraper.readthedocs.io/
repo_url: https://github.com/AliAkhtari78/SpotifyScraper
repo_name: AliAkhtari78/SpotifyScraper
copyright: Copyright &copy; 2025 Ali Akhtari - Documentation Last Updated May 2025

theme:
  name: simple-blog
  custom_dir: null
  locale: en
  theme:
    language: en
    features:
      - content.code.annotate
      - content.tabs.link
      - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono
  logo: null
  favicon: null
  include_search_page: true
  search_index_only: true
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
    - json
    - xml
  hljs_style: github
  navigation_depth: 2
  nav_style: dark
  shortcuts:
    help: 191      # ?
    next: 78       # n
    previous: 80   # p
    search: 83     # s

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Introduction: guide/index.md
    - Basic Usage: guide/basic-usage.md
    - Authentication: guide/authentication.md
    - Error Handling: guide/error-handling.md
    - Media Downloads: guide/media-downloads.md
  - API Reference:
    - Overview: api/index.md
    - Client: api/client.md
    - Extractors: api/extractors.md
    - Media: api/media.md
    - Utils: api/utils.md
    - Parsers: api/parsers.md
    - Exceptions: api/exceptions.md
  - Examples:
    - Overview: examples/index.md
    - Quick Start: examples/quickstart.md
    - CLI Usage: examples/cli.md
    - Bulk Operations: examples/bulk_operations.md
    - Advanced Usage: examples/advanced.md
    - Real-World Projects: examples/projects.md
  - Advanced Topics:
    - Overview: advanced/index.md
    - Architecture: advanced/architecture.md
    - Custom Extractors: advanced/custom-extractors.md
    - Performance: advanced/performance.md
    - Scaling: advanced/scaling.md
  - Additional Resources:
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
    - Migration Guide: migration.md
    - Changelog: changelog.md
    - Contributing: contributing.md
    - Features: features.md
    - Testing Guide: README_TESTING.md
    - MCP Testing: mcp_testing.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - codehilite:
      guess_lang: false
  - tables
  - attr_list
  - def_list
  - footnotes
  - nl2br
  - sane_lists

extra:
  version: 2.0.0
  author: Ali Akhtari
  year: 2025
  social:
    - name: GitHub
      link: https://github.com/AliAkhtari78/SpotifyScraper
      icon: github
    - name: PyPI
      link: https://pypi.org/project/spotifyscraper/
      icon: python
  generator: false
  blog:
    dir: blog
    author: Ali Akhtari
    author_image: null
    words_read_per_minute: 200

plugins:
  - search