"""URL/header construction and envelope decoding for Spotify transcripts.

The transcript host (``spclient.wg.spotify.com``) is the same authenticated
web-player host as color-lyrics and is reached with the same cookie-derived
token. These helpers are I/O-free; the sync and async facades reuse them.

The live response (confirmed against ``transcript-read-along/v2``) is plain
JSON: a top-level ``language`` plus a ``section`` array whose items are either a
spoken cue (``section[i].text.sentence.text`` with a ``startMs``), a music cue
(``section[i].fallback.sentence.text``), or a speaker label
(``section[i].title.title`` — no spoken text). :func:`decode_envelope`
normalizes that into a single mapping the parser consumes, and is the one place
to adjust if Spotify changes the wire format — mirroring how pathfinder hashes
are confined to one module.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, TypeGuard

_TRANSCRIPT_BASE = "https://spclient.wg.spotify.com/transcript-read-along/v2/episode"
_TRANSCRIPT_QUERY = "format=json"

#: Keys the response may carry its array of cues under.
_CUE_CONTAINER_KEYS = ("section", "segments", "timedText", "lines", "cues")
#: Within a cue, the wrappers that hold a ``sentence`` of spoken/caption text.
_SENTENCE_WRAPPER_KEYS = ("text", "fallback")
#: Keys a plain (already-flat) cue may carry its start offset under.
_START_KEYS = ("startMs", "start_ms", "time_ms", "timeMs", "startTimeMs")
#: Keys a plain (already-flat) cue may carry its text string under.
_TEXT_KEYS = ("text", "transcription", "words", "content")


def transcript_url(episode_id: str) -> str:
    """Return the transcript-read-along URL for an episode ID.

    Args:
        episode_id: The 22-character Spotify episode ID.

    Returns:
        The fully-qualified transcript request URL.
    """
    return f"{_TRANSCRIPT_BASE}/{episode_id}?{_TRANSCRIPT_QUERY}"


def auth_headers(token: str) -> dict[str, str]:
    """Return the authorization headers for a transcript request.

    Args:
        token: A cookie-derived web-player bearer token.

    Returns:
        Headers carrying the bearer token and the web-player platform marker.
    """
    return {"Authorization": f"Bearer {token}", "app-platform": "WebPlayer"}


def decode_envelope(body: Mapping[str, Any]) -> dict[str, Any]:
    """Normalize a transcript response body into the parser's contract.

    The return value is always shaped as::

        {"lines": [{"start_ms": int, "text": str}, ...],
         "language": str | None, "provider": str | None,
         "isAutoGenerated": bool | None}

    Cues are read from the ``section`` array (or another known container key).
    Each cue's text is taken from ``text.sentence.text`` (spoken) or
    ``fallback.sentence.text`` (music), with a tolerant fallback to a flat
    ``text`` string; speaker-label cues (``title`` only) yield no line.

    Args:
        body: The decoded transcript response body.

    Returns:
        The normalized mapping. When no lines can be recovered the ``"lines"``
        key is omitted, so :func:`parse_transcript` raises :class:`ParsingError`.
    """
    meta = {
        "language": _str_or_none(body.get("language")),
        "provider": _str_or_none(body.get("provider")),
        "isAutoGenerated": _bool_or_none(body.get("isAutoGenerated")),
    }
    lines = _lines_from_json(body)
    if lines is None:
        return meta
    return {"lines": lines, **meta}


def _lines_from_json(body: Mapping[str, Any]) -> list[dict[str, Any]] | None:
    """Map the first recognized cue container into normalized lines, else ``None``."""
    for key in _CUE_CONTAINER_KEYS:
        cues = _as_cue_sequence(body.get(key))
        if cues is None:
            continue
        lines: list[dict[str, Any]] = []
        for cue in cues:
            if not isinstance(cue, Mapping):
                continue
            line = _cue_to_line(cue)
            if line is not None:
                lines.append(line)
        return lines
    return None


def _cue_to_line(cue: Mapping[str, Any]) -> dict[str, Any] | None:
    """Extract one normalized line from a cue, or ``None`` for a non-text cue."""
    for wrapper_key in _SENTENCE_WRAPPER_KEYS:
        wrapper = cue.get(wrapper_key)
        if isinstance(wrapper, Mapping):
            sentence = wrapper.get("sentence")
            if isinstance(sentence, Mapping):
                text = sentence.get("text")
                if isinstance(text, str) and text:
                    start = sentence.get("startMs", cue.get("startMs", 0))
                    return {"start_ms": start, "text": text}
    # Tolerant fallback: a flat cue carrying its text directly as a string.
    text = _first_str(cue, _TEXT_KEYS)
    if text:
        return {"start_ms": _first_start(cue), "text": text}
    return None  # speaker-label / empty cue


def _as_cue_sequence(container: Any) -> Sequence[Any] | None:
    """Return the list of cues from a container node, else ``None``."""
    if isinstance(container, Mapping):
        for key in _CUE_CONTAINER_KEYS:
            inner = container.get(key)
            if _is_cue_list(inner):
                return inner
        return None
    if _is_cue_list(container):
        return container
    return None


def _is_cue_list(value: Any) -> TypeGuard[Sequence[Any]]:
    return isinstance(value, Sequence) and not isinstance(value, (str, bytes))


def _first_start(cue: Mapping[str, Any]) -> Any:
    for key in _START_KEYS:
        if key in cue:
            return cue[key]
    return 0


def _first_str(cue: Mapping[str, Any], keys: tuple[str, ...]) -> str:
    for key in keys:
        value = cue.get(key)
        if isinstance(value, str):
            return value
    return ""


def _str_or_none(value: Any) -> str | None:
    return value if isinstance(value, str) else None


def _bool_or_none(value: Any) -> bool | None:
    return value if isinstance(value, bool) else None
