"""URL/header construction and envelope decoding for Spotify transcripts.

The transcript host (``spclient.wg.spotify.com``) is the same authenticated
web-player host as color-lyrics and is reached with the same cookie-derived
token. These helpers are I/O-free; the sync and async facades reuse them.

NOTE: The exact live 200-body shape is **unconfirmed** (see
``openspec/changes/add-podcast-transcripts/design.md``, the open verification
item). :func:`decode_envelope` is the single place to fix when a live capture
confirms the wire format — it normalizes whatever Spotify returns (plain JSON
cues, or a JSON envelope wrapping a base64 protobuf blob) into one mapping the
parser consumes. The host/path/query live ONLY in this module so a Spotify
change is a one-line edit, mirroring how pathfinder hashes are confined.
"""

from __future__ import annotations

import base64
import binascii
from collections.abc import Mapping, Sequence
from typing import Any, TypeGuard

_TRANSCRIPT_BASE = "https://spclient.wg.spotify.com/transcript-read-along/v2/episode"
_TRANSCRIPT_QUERY = "format=json"

#: Keys a plain-JSON body may carry its list of cues under.
_CUE_CONTAINER_KEYS = ("section", "segments", "timedText", "lines", "cues")
#: Keys a plain-JSON cue may carry its start offset under.
_START_KEYS = ("startMs", "start_ms", "time_ms", "timeMs", "startTimeMs")
#: Keys a plain-JSON cue may carry its text under.
_TEXT_KEYS = ("text", "transcription", "words", "content")
#: Keys an envelope may carry its base64 protobuf transcript blob under.
_BLOB_KEYS = ("transcript", "transcriptText", "transcriptData", "data")


def transcript_url(episode_id: str) -> str:
    """Return the transcript-read-along URL for an episode ID.

    Args:
        episode_id: The 22-character Spotify episode ID.

    Returns:
        The fully-qualified transcript request URL.
    """
    return f"{_TRANSCRIPT_BASE}/{episode_id}?{_TRANSCRIPT_QUERY}"


def auth_headers(token: str) -> dict[str, str]:
    """Return the authorization headers for a transcript request.

    Args:
        token: A cookie-derived web-player bearer token.

    Returns:
        Headers carrying the bearer token and the web-player platform marker.
    """
    return {"Authorization": f"Bearer {token}", "app-platform": "WebPlayer"}


def decode_envelope(body: Mapping[str, Any]) -> dict[str, Any]:
    """Normalize a transcript response body into the parser's contract.

    The return value is always shaped as::

        {"lines": [{"start_ms": int, "text": str}, ...],
         "language": str | None, "provider": str | None,
         "isAutoGenerated": bool | None}

    Two input shapes are tolerated (see module NOTE):

    1. A plain-JSON body whose cues live under a ``section`` / ``segments`` /
       ``timedText`` / ``lines``-ish key, each cue carrying text and a start
       offset (any of ``startMs`` / ``start_ms`` / ``time_ms`` / ``timeMs`` /
       ``startTimeMs``).
    2. A JSON envelope carrying a base64 protobuf blob under a transcript-ish
       string key — base64-decoded then read with a tiny protobuf-wire reader
       (community schema: field 4 = repeated ``segments``; each segment field 2
       = ``time_ms`` varint, field 3 = ``transcription`` message whose field 1
       = repeated string text, joined).

    Args:
        body: The decoded transcript response body.

    Returns:
        The normalized mapping. When no lines can be recovered the ``"lines"``
        key is omitted, so :func:`parse_transcript` raises :class:`ParsingError`.
    """
    meta = {
        "language": _str_or_none(body.get("language")),
        "provider": _str_or_none(body.get("provider")),
        "isAutoGenerated": _bool_or_none(body.get("isAutoGenerated")),
    }

    lines = _lines_from_json(body)
    if lines is None:
        lines = _lines_from_blob(body)
    if lines is None:
        return meta
    return {"lines": lines, **meta}


def _lines_from_json(body: Mapping[str, Any]) -> list[dict[str, Any]] | None:
    """Map a plain-JSON cue container into normalized lines, else ``None``."""
    for key in _CUE_CONTAINER_KEYS:
        container = body.get(key)
        cues = _as_cue_sequence(container)
        if cues is None:
            continue
        lines: list[dict[str, Any]] = []
        for cue in cues:
            if not isinstance(cue, Mapping):
                continue
            text = _first_str(cue, _TEXT_KEYS)
            lines.append({"start_ms": _first_start(cue), "text": text})
        return lines
    return None


def _as_cue_sequence(container: Any) -> Sequence[Any] | None:
    """Return the list of cues from a container node, else ``None``."""
    if isinstance(container, Mapping):
        for key in _CUE_CONTAINER_KEYS:
            inner = container.get(key)
            if _is_cue_list(inner):
                return inner
        return None
    if _is_cue_list(container):
        return container
    return None


def _is_cue_list(value: Any) -> TypeGuard[Sequence[Any]]:
    return isinstance(value, Sequence) and not isinstance(value, (str, bytes))


def _lines_from_blob(body: Mapping[str, Any]) -> list[dict[str, Any]] | None:
    """Base64-decode a protobuf blob and read its segments, else ``None``."""
    for key in _BLOB_KEYS:
        blob = body.get(key)
        if not isinstance(blob, str) or not blob:
            continue
        try:
            raw = base64.b64decode(blob, validate=True)
        except (binascii.Error, ValueError):
            continue
        lines = _read_segments(raw)
        if lines:
            return lines
    return None


# --------------------------------------------------------------------------- #
# Tiny protobuf-wire reader (varint + length-delimited only, no dependency)
# --------------------------------------------------------------------------- #


def _read_segments(raw: bytes) -> list[dict[str, Any]]:
    """Read top-level field 4 (repeated ``segments``) from a protobuf message.

    Each segment: field 2 = ``time_ms`` (varint), field 3 = ``transcription``
    message whose field 1 = repeated string text (joined).
    """
    lines: list[dict[str, Any]] = []
    for field_num, wire_type, value in _read_fields(raw):
        if field_num == 4 and wire_type == 2 and isinstance(value, bytes):
            lines.append(_read_segment(value))
    return lines


def _read_segment(raw: bytes) -> dict[str, Any]:
    start_ms = 0
    parts: list[str] = []
    for field_num, wire_type, value in _read_fields(raw):
        if field_num == 2 and wire_type == 0 and isinstance(value, int):
            start_ms = value
        elif field_num == 3 and wire_type == 2 and isinstance(value, bytes):
            parts.extend(_read_transcription(value))
    return {"start_ms": start_ms, "text": " ".join(parts)}


def _read_transcription(raw: bytes) -> list[str]:
    parts: list[str] = []
    for field_num, wire_type, value in _read_fields(raw):
        if field_num == 1 and wire_type == 2 and isinstance(value, bytes):
            parts.append(value.decode("utf-8", "replace"))
    return parts


def _read_fields(raw: bytes) -> list[tuple[int, int, int | bytes]]:
    """Decode a protobuf message into ``(field_number, wire_type, value)``.

    Only varint (wire type 0) and length-delimited (wire type 2) are handled;
    any other wire type stops the scan (these messages use no others).
    """
    fields: list[tuple[int, int, int | bytes]] = []
    pos = 0
    length = len(raw)
    while pos < length:
        tag, pos = _read_varint(raw, pos)
        if pos < 0:
            break
        field_num = tag >> 3
        wire_type = tag & 0x07
        if wire_type == 0:
            value, pos = _read_varint(raw, pos)
            if pos < 0:
                break
            fields.append((field_num, wire_type, value))
        elif wire_type == 2:
            size, pos = _read_varint(raw, pos)
            if pos < 0 or pos + size > length:
                break
            fields.append((field_num, wire_type, raw[pos : pos + size]))
            pos += size
        else:
            break
    return fields


def _read_varint(raw: bytes, pos: int) -> tuple[int, int]:
    """Read a base-128 varint at ``pos``; return ``(value, next_pos)``.

    On a truncated varint the next position is ``-1``.
    """
    result = 0
    shift = 0
    length = len(raw)
    while pos < length:
        byte = raw[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, pos
        shift += 7
    return 0, -1


def _first_start(cue: Mapping[str, Any]) -> Any:
    for key in _START_KEYS:
        if key in cue:
            return cue[key]
    return 0


def _first_str(cue: Mapping[str, Any], keys: tuple[str, ...]) -> str:
    for key in keys:
        value = cue.get(key)
        if isinstance(value, str):
            return value
    return ""


def _str_or_none(value: Any) -> str | None:
    return value if isinstance(value, str) else None


def _bool_or_none(value: Any) -> bool | None:
    return value if isinstance(value, bool) else None
