name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      # Allow Spotify embeds and other custom hosts
      COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: |
        open.spotify.com,
        spotify.com,
        google.com,
        github.com,
        githubusercontent.com,
        raw.githubusercontent.com,
        gist.githubusercontent.com,
        assets-cdn.github.com,
        avatars.githubusercontent.com,
        cloud.githubusercontent.com,
        api.github.com,
        copilot-telemetry.githubusercontent.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Use a specific Python version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev python3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install lxml==4.5.0 --no-build-isolation
          pip install -r requirements.txt

      - name: Run embed URL test
        run: python test_embed_url.py
