name: Dependency Review

on:
  pull_request:
    paths:
      - 'requirements*.txt'
      - 'setup.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Pipfile.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        deny-licenses: GPL-3.0, AGPL-3.0
        comment-summary-in-pr: always