name: Deploy GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create and push to gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create orphan gh-pages branch
          git checkout --orphan gh-pages
          
          # Remove all files
          git rm -rf .
          
          # Create minimal site
          echo '<!DOCTYPE html>' > index.html
          echo '<html>' >> index.html
          echo '<head>' >> index.html
          echo '    <meta charset="utf-8">' >> index.html
          echo '    <title>SpotifyScraper Documentation</title>' >> index.html
          echo '    <meta http-equiv="refresh" content="0; url=https://spotifyscraper.readthedocs.io/">' >> index.html
          echo '    <link rel="canonical" href="https://spotifyscraper.readthedocs.io/">' >> index.html
          echo '</head>' >> index.html
          echo '<body>' >> index.html
          echo '    <h1>Redirecting to SpotifyScraper Documentation...</h1>' >> index.html
          echo '    <p>If you are not redirected automatically, please visit <a href="https://spotifyscraper.readthedocs.io/">https://spotifyscraper.readthedocs.io/</a></p>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
          
          # Create .nojekyll
          touch .nojekyll
          
          # Add and commit
          git add index.html .nojekyll
          git commit -m "Deploy GitHub Pages"
          
          # Push to gh-pages branch
          git push -f origin gh-pages